Read the data and KNN

read the data

In [1]:
import numpy as np
import os
import matplotlib.pyplot as plt

datasets_dir = 'media/datasets/'

def one_hot(x,n):
	if type(x) == list:
		x = np.array(x)
	x = x.flatten()
	o_h = np.zeros((len(x),n))
	o_h[np.arange(len(x)),x] = 1
	return o_h

def mnist(ntrain=60000,ntest=10000,onehot=True):
	data_dir = os.path.join(datasets_dir,'mnist/')
	fd = open("train-images.idx3-ubyte", 'rb')
	loaded = np.fromfile(file=fd,dtype=np.uint8)
	trX = loaded[16:].reshape((60000,28*28)).astype(float)

	fd = open("train-labels.idx1-ubyte", 'rb')
	loaded = np.fromfile(file=fd,dtype=np.uint8)
	trY = loaded[8:].reshape((60000))

	fd = open("t10k-images.idx3-ubyte", 'rb')
	loaded = np.fromfile(file=fd,dtype=np.uint8)
	teX = loaded[16:].reshape((10000,28*28)).astype(float)

	fd = open("t10k-labels.idx1-ubyte", 'rb')
	loaded = np.fromfile(file=fd,dtype=np.uint8)
	teY = loaded[8:].reshape((10000))

	trX = trX/255.
	teX = teX/255.

	trX = trX[:ntrain]
	trY = trY[:ntrain]

	teX = teX[:ntest]
	teY = teY[:ntest]

	if onehot:
		trY = one_hot(trY, 10)
		teY = one_hot(teY, 10)
	else:
		trY = np.asarray(trY)
		teY = np.asarray(teY)

	return trX,teX,trY,teY

Xtrain, Xtest, Ytrain, Ytest = mnist()

KNN Method

In [2]:
import matplotlib.pyplot as plt

from sklearn import cross_validation
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

import numpy as np
import pickle



"""
#Features
X = train_img

#Labels
y = train_labels
"""
print('\nPreparing Classifier Training and Testing Data...')
Xtrain, Xtest, Ytrain, Ytest = cross_validation.train_test_split(Xtrain,Ytrain,test_size=0.1)


print('\nKNN Classifier with n_neighbors = 5, algorithm = auto, n_jobs = 10')
print('\nPickling the Classifier for Future Use...')
clf = KNeighborsClassifier(n_neighbors=5,algorithm='auto',n_jobs=10)
clf.fit(Xtrain,Ytrain)

with open('MNIST_KNN.pickle','wb') as f:
	pickle.dump(clf, f)

pickle_in = open('MNIST_KNN.pickle','rb')
clf = pickle.load(pickle_in)

print('\nCalculating Accuracy of trained Classifier...')
acc = clf.score(Xtest,Ytest)

print('\nMaking Predictions on Testing Data...')
pred = clf.predict(Xtest)

print('\nCalculating Accuracy of Predictions...')
accuracy = accuracy_score(Ytest, pred)

print('\nCalculating Confusion Matrix...')
preds = net1.predict(Xtest)  
cm = confusion_matrix(Ytest, preds)

print('\nKNN Trained Classifier Accuracy: ',acc)
print('\nPredicted Values: ',pred)
print('\nConfusion Matrix: ',cm)
print('\nAccuracy of Classifier on Test Images: ',accuracy)


Preparing Classifier Training and Testing Data...

KNN Classifier with n_neighbors = 5, algorithm = auto, n_jobs = 10

Pickling the Classifier for Future Use...

Calculating Accuracy of trained Classifier...

Making Predictions on Testing Data...

Calculating Accuracy of Predictions...

Calculating Confusion Matrix...

KNN Trained Classifier Accuracy:  0.978833333333

Predicted Values:  [7 2 1 ..., 4 5 6]

Confusion Matrix:
 [[ 974    1    1    0    0    0    2    1    1    0]
 [   0 1133    2    0    0    0    0    0    0    0]
 [  10   13  983    3    2    0    1   16    4    0]
 [   0    3    2  979    1   12    1    6    4    2]
 [   2    8    0    0  942    0    4    2    1   23]
 [   5    0    0   15    1  858    4    2    2    5]
 [   6    3    0    0    3    2  944    0    0    0]
 [   0   25    4    0    2    0    0  986    0   11]
 [   8    4    6   14    7   15    2    6  907    5]
 [   7    6    2    9    7    3    1   11    2  961]]

Accuracy of Classifier on Test Images: