Random Forest Classifier

read data

In [1]:
import numpy as np
import os
import matplotlib.pyplot as plt

datasets_dir = 'media/datasets/'

def one_hot(x,n):
	if type(x) == list:
		x = np.array(x)
	x = x.flatten()
	o_h = np.zeros((len(x),n))
	o_h[np.arange(len(x)),x] = 1
	return o_h

def mnist(ntrain=60000,ntest=10000,onehot=False):
	data_dir = os.path.join(datasets_dir,'mnist/')
	fd = open("train-images.idx3-ubyte", 'rb')
	loaded = np.fromfile(file=fd,dtype=np.uint8)
	trX = loaded[16:].reshape((60000,28*28)).astype(float)

	fd = open("train-labels.idx1-ubyte", 'rb')
	loaded = np.fromfile(file=fd,dtype=np.uint8)
	trY = loaded[8:].reshape((60000))

	fd = open("t10k-images.idx3-ubyte", 'rb')
	loaded = np.fromfile(file=fd,dtype=np.uint8)
	teX = loaded[16:].reshape((10000,28*28)).astype(float)

	fd = open("t10k-labels.idx1-ubyte", 'rb')
	loaded = np.fromfile(file=fd,dtype=np.uint8)
	teY = loaded[8:].reshape((10000))

	trX = trX/255.
	teX = teX/255.

	trX = trX[:ntrain]
	trY = trY[:ntrain]

	teX = teX[:ntest]
	teY = teY[:ntest]

	if onehot:
		trY = one_hot(trY, 10)
		teY = one_hot(teY, 10)
	else:
		trY = np.asarray(trY)
		teY = np.asarray(teY)

	return trX,teX,trY,teY

Xtrain, Xtest, Ytrain, Ytest = mnist()

RFC

In [2]:
import matplotlib.pyplot as plt

from sklearn import cross_validation
from sklearn.ensemble import RandomForestClassifier

import numpy as np
import pickle

# Prepare Classifier Training and Testing Data
print('\nPreparing Classifier Training and Testing Data...')
Xtrain, Xtest, Ytrain, Ytest = cross_validation.train_test_split(Xtrain,Ytrain,test_size=0.1)


# Pickle the Classifier for Future Use
print('\nRFC Classifier with n_estimators = 100; n_jobs = 10)
print('\nPickling the Classifier for Future Use...')
clf = RandomForestClassifier(n_estimators=100, n_jobs=10,)
clf.fit(Xtrain,Ytrain)

with open('MNIST_RFC.pickle','wb') as f:
	pickle.dump(clf, f)

pickle_in = open('MNIST_RFC.pickle','rb')
clf = pickle.load(pickle_in)

print('\nCalculating Accuracy of trained Classifier...')
acc = clf.score(Xtest,Ytest)

print('\nMaking Predictions on Testing Data...')
pred = clf.predict(Xtest)

print('\nCalculating Accuracy of Predictions...')
accuracy = accuracy_score(Ytest, pred)

print('\nCalculating Confusion Matrix...')
preds = net1.predict(Xtest)  
cm = confusion_matrix(Ytest, preds)

print('\nRFC Trained Classifier Accuracy: ',acc)
print('\nPredicted Values: ',pred)
print('\nConfusion Matrix: ',cm)
print('\nAccuracy of Classifier on Test Images: ',accuracy)


Preparing Classifier Training and Testing Data...

RFC Classifier with n_estimators = 100; n_jobs = 10

Pickling the Classifier for Future Use...

Calculating Accuracy of trained Classifier...

Making Predictions on Testing Data...

Calculating Confusion Matrix...

Calculating Accuracy of Predictions...

RFC Trained Classifier Accuracy:  0.997166666667

Predicted Values:  [7 2 1 ..., 4 5 6]

Confusion Matrix:
 [[ 972    0    0    0    0    2    2    1    3    0]
 [   0 1122    2    4    2    1    3    0    1    0]
 [   6    0  993    5    5    1    4   11    7    0]
 [   0    0   10  966    0   11    0    9   11    3]
 [   1    0    1    0  956    0    4    0    3   17]
 [   3    0    1   10    1  862    4    2    5    4]
 [   7    3    0    0    3    3  938    0    4   10]
 [   1    6   19    1    1    0    0  986    4   10]
 [   4    0    4   10    4    4    5    5  931    7]
 [   6    6    2   11   11    1    1    4    4  963]]

Accuracy of Classifier on Test Images:  0.9689
